### ISSUE TITLE
Rewrite this in Rust.

### ISSUE THREAD

**Issue by chronium** [alkalinethunder/pandemic-framework#4]
Hello!

Could you kindly rewrite this in Rust?
Here's a library capable of that: https://amethyst.rs/

Thank you and have a nice day!

**Comment by alkalinethunder** [comment]
Gonna have to say no to that one, that's not a language I know at all and I'm way too busy with college to learn it.  C++ would be one of my ideal languages but then it'd just be another game engine.  .NET Core really deserves some love in my opinion because it's both fast and cross-platform but with the same simplicity and power that got me into gamedev as a kid.

Closing.
